services:
  cert-generator:
    image: alpine/openssl
    container_name: reverse-proxy-cert-generator
    user: "0:0"
    entrypoint: [ "sh", "-c", "chmod +x /scripts/* && /scripts/generate-crt.sh" ]
    volumes:
    - "./scripts:/scripts"
    - "./traefik/certs:/traefik/certs"

  traefik:
    image: traefik:v3.4.3
    container_name: reverse-proxy-traefik
    restart: always
    depends_on:
      cert-generator:
        condition: service_completed_successfully
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
    networks:
      - "backend"

  mariadb:
    image: mariadb:11.8.2
    container_name: reverse-proxy-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=database
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    labels:
      - "traefik.enable=false"
    networks:
      - "backend"

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: reverse-proxy-phpmyadmin
    restart: always
    volumes:
    - ./phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - "backend"

networks:
    backend:
        external: true

volumes:
    mariadb:
        driver: local
