################################################################
# TLS Configuration
################################################################
tls:
  options:
    default:
      minVersion: VersionTLS12
  certificates:
    - certFile: /etc/traefik/certs/fullchain.crt
      keyFile: /etc/traefik/certs/localhost.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/fullchain.crt
        keyFile: /etc/traefik/certs/localhost.key
