################################################################
# TLS Configuration
################################################################
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
  certificates:
    - certFile: /etc/traefik/certs/localhost.crt
      keyFile: /etc/traefik/certs/localhost.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/localhost.crt
        keyFile: /etc/traefik/certs/localhost.key
